[workspace]
members = ["noveltui", "webnovel", "theme"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
textwrap = "0.16.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = "symbols"
