name: Rust

on:
  push:
    branches: 
      - "main"
      - "dev"
      - "net_reader"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "net_reader"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
